defaults: &defaults
    working_directory: ~/app
    steps:
        - checkout
        - run:
            name: Install Dependencies
            command: yarn install
        - run:
            name: Migrate
            command: npm run migrate
        - run:
            name: Unit test and API test
            command: npm run test -- --timeout 30s
        - run:
            name: Lint
            command: npm run lint

version: 2
jobs:
    build-node-lts:
        <<: *defaults
        docker:
            - image: node:10
              environment:
                  MONGODB_URI: mongodb://localhost
                  MONGODB_DBNAME: goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
                  JWT_SECRET: DontUseMe
                  VERIFY_EMAIL_JWT_SECRET: DontUseMe
            - image: mongo:3
            - image: redis
    build-node-current:
        <<: *defaults
        docker:
            - image: node:12
              environment:
                  MONGODB_URI: mongodb://localhost
                  MONGODB_DBNAME: goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
                  JWT_SECRET: DontUseMe
                  VERIFY_EMAIL_JWT_SECRET: DontUseMe
            - image: mongo:3
            - image: redis
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-node-lts
            - build-node-current
