const UNVERIFIED = "UNVERIFIED";
const SENT_VERIFICATION_LINK = "SENT_VERIFICATION_LINK";
const VERIFIED = "VERIFIED";

const EMAIL_STATUS = {
    UNVERIFIED,
    SENT_VERIFICATION_LINK,
    VERIFIED,
};

module.exports = EMAIL_STATUS;
